### ISSUE TITLE
About SVD.model 

### ISSUE THREAD

**Issue by nbnbhwyy** [mustafaCoskunAgu/SiGraC#2]
Hi authors,

Thanks for your  works. But I don’t seem to be able to find any SVD related files, I hope I can get your help.

     File "main.py", line 14, in <module>
        from embed_train import embedding_training, load_embedding, read_node_labels, split_train_test_graph
      File "/mnt/rao/home/chenhg/Methods/SiGraC-main/embed_train.py", line 12, in <module>
        from SVD.model import SVD_embedding
    ModuleNotFoundError: No module named 'SVD'

**Comment by mustafaCoskunAgu** [comment]
Hi,
Thanks for the question. The code does not use SVD, please just comment it out to proceed.
Best,
